[build]
  publish = "dist"
  command = "npm run generate"
[build.environment]
  NODE_VERSION = "11"
[[plugins]]
  package = "@netlify/plugin-sitemap"
  
	[plugins.inputs]
	
	buildDir = "dist"
	exclude = ['./dist/admin','./dist/200','/dist/200.html']
[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]

	# The base url of your site (optional, default = main URL set in Netlify)
	baseUrl = "https://cameronwickes.com"

	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap.xml"

	# Enabled providers to submit sitemap to (optional, default = 'google', 'bing'). Possible providers are currently only 'google' and 'bing'.
	providers = [
		"google",
		"bing"
	]
	
[[plugins]]
  package = "netlify-plugin-debug-cache"
  
[[plugins]]
  package = "netlify-deployment-hours-plugin"

	  [plugins.inputs]
	  # A cron-like expression that expresses when a deployment can occur
	  expression = "* * * * *"
	  # tz database value that expresses the timezone of the expression
	  timezone = "GMT"
